# Generated by Django 5.2.1 on 2025-07-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ctgry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.category'),
        ),
    ]
