# Generated by Django 5.2.1 on 2025-07-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_book_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='returned_date',
        ),
    ]
