# Generated by Django 5.2.1 on 2025-09-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0014_language_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
